<a id="table_of_content"></a>

# Part 1: Bag-of-Words Exercises

In the following, we will convert our corpus of 10-k documents into bag-of-words, and convert them into document vectors using Term-Frequency-Inverse-Document-Frequency (tf-idf) re-weighting. Afterward, we will compute sentiments and similarity metrics. Since we will be reusing our notebook, so the various sections are linked below:

1. <a href="#bag_of_word">Compute bag-of-words </a>: implement `bag_of_words` that converts tokenized words into a dictionary of word-counts

2. <a href="#sentiment">Sentiments </a>: using wordlists, compute positive and negative sentiments from bag-of-words. Implement `get_sentiment`

For solutions, see [bagofwords_solutions.py](./bagofwords_solutions.py). You can load the functions by simply calling 

`from bagofwords_solutions import *`

# Part 2: Document-Vector Exercises

3. <a href="#compute_idf">Compute idf </a>: computing the inverse document frequency, implement `get_idf`

4. <a href="#compute_tf">Compute tf </a>: computing the term frequency, implement `get_tf`

5. <a href="#doc_vector">Document vector </a>: using the functions `get_idf` and `get_tf`, compute a word_vector for each document in the corpus
6. <a href="#similarity">Similarities </a>: comparing two vectors, and compute cosine and jacard similarity metrics. Implement `get_cos` and `get_jac`

For solutions, see [bagofwords_solutions.py](./bagofwords_solutions.py). You can load the functions by simply calling 

`from bagofwords_solutions import *`


## 0. Initialization

First we read in our 10-k documents

In [1]:
# download some excerpts from 10-K files
from download10k import get_files

CIK = {'ebay': '0001065088', 'apple':'0000320193', 'sears': '0001310067'}
get_files(CIK['ebay'], 'EBAY')
get_files(CIK['apple'], 'AAPL')
get_files(CIK['sears'], 'SHLDQ')


# get a list of all 10-ks in our directory
files=! ls *10k*.txt
print("10-k files: ",files)
files = [open(f,"r").read() for f in files]

downloading 10-Ks item 1A for CIK = 0001065088 ...
writing EBAY_10k_2017.txt...
writing EBAY_10k_2016.txt...
writing EBAY_10k_2015.txt...
writing EBAY_10k_2014.txt...
writing EBAY_10k_2013.txt...
downloading 10-Ks item 1A for CIK = 0000320193 ...
downloading 10-Ks item 1A for CIK = 0001310067 ...
writing SHLDQ_10k_2017.txt...
writing SHLDQ_10k_2016.txt...
writing SHLDQ_10k_2015.txt...
writing SHLDQ_10k_2014.txt...
writing SHLDQ_10k_2013.txt...
10-k files:  ['EBAY_10k_2013.txt', 'EBAY_10k_2014.txt', 'EBAY_10k_2015.txt', 'EBAY_10k_2016.txt', 'EBAY_10k_2017.txt', 'SHLDQ_10k_2013.txt', 'SHLDQ_10k_2014.txt', 'SHLDQ_10k_2015.txt', 'SHLDQ_10k_2016.txt', 'SHLDQ_10k_2017.txt']


here we define useful functions to tokenize the texts into words, remove stop-words, and lemmatize and stem our words

In [2]:
import numpy as np

# for nice number printing
np.set_printoptions(precision=3, suppress=True)

# tokenize and clean the text
import nltk
from nltk.stem import WordNetLemmatizer, SnowballStemmer
from collections import Counter
from nltk.corpus import stopwords
from nltk import word_tokenize
from nltk.tokenize import RegexpTokenizer
# tokenize anything that is not a number and not a symbol
word_tokenizer = RegexpTokenizer(r'[^\d\W]+')

nltk.download('stopwords')
nltk.download('wordnet')


sno = SnowballStemmer('english')
wnl = WordNetLemmatizer()

# get our list of stop_words
nltk.download('stopwords')
stop_words = set(stopwords.words('english')) 
# add some extra stopwords
stop_words |= {"may", "business", "company", "could", "service", "result", "product", 
               "operation", "include", "law", "tax", "change", "financial", "require",
               "cost", "market", "also", "user", "plan", "actual", "cash", "other",
               "thereto", "thereof", "therefore"}

# useful function to print a dictionary sorted by value (largest first by default)
def print_sorted(d, ascending=False):
    factor = 1 if ascending else -1
    sorted_list = sorted(d.items(), key=lambda v: factor*v[1])
    for i, v in sorted_list:
        print("{}: {:.3f}".format(i, v))

# convert text into bag-of-words
def clean_text(txt):
    lemm_txt = [ wnl.lemmatize(wnl.lemmatize(w.lower(),'n'),'v') \
                for w in word_tokenizer.tokenize(txt) if \
                w.isalpha() and w not in stop_words ]
    return [ sno.stem(w) for w in lemm_txt if w not in stop_words and len(w) > 2 ]

corpus = [clean_text(f) for f in files]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [3]:
corpus


[['risk',
  'factor',
  'affect',
  'condit',
  'subject',
  'various',
  'risk',
  'uncertainti',
  'advers',
  'affect',
  'condit',
  'flow',
  'well',
  'trade',
  'price',
  'common',
  'stock',
  'debt',
  'offer',
  'oper',
  'vari',
  'quarter',
  'basi',
  'oper',
  'histori',
  'oper',
  'fluctuat',
  'signific',
  'varieti',
  'factor',
  'mani',
  'outsid',
  'control',
  'factor',
  'affect',
  'oper',
  'risk',
  'describ',
  'elsewher',
  'section',
  'follow',
  'general',
  'econom',
  'condit',
  'possibl',
  'prolong',
  'period',
  'limit',
  'econom',
  'growth',
  'possibl',
  'econom',
  'declin',
  'europ',
  'advers',
  'effect',
  'ongo',
  'sovereign',
  'debt',
  'crisi',
  'europ',
  'increas',
  'euro',
  'currenc',
  'exchang',
  'rate',
  'volatil',
  'negat',
  'impact',
  'crisi',
  'relat',
  'auster',
  'measur',
  'european',
  'econom',
  'growth',
  'potenti',
  'negat',
  'spillov',
  'effect',
  'rest',
  'world',
  'contagion',
  'risk',
  'cri

<a id="bag_of_words"></a>

## 1. Bag-of-Words

Implement a function that converts a list of tokenized words into bag-of-words, i.e. a dictionary that outputs the frequency count of a word

** python already provide the `collections.Counter` class to perform this, but I encourage you to implement your own function as an exercise

<a href="#table_of_content">back to top</a>

In [4]:
from collections import defaultdict

def bag_of_words(words):
    bag = defaultdict(int)
    for w in words:
        bag[w] += 1
    return bag

<a id="sentiment"></a>

## 2. Sentiments
Count the fraction of words that appear in a wordlist, returning a sentiment score between 0 and 1:

$$
\textrm{score} = \frac{\textrm{Number of words in document matching wordlist}}{\textrm{Number of words in document}}
$$

Implement the score in a function `get_sentiment(words, wordlist)`, where words is a list of words. Feel free to use the previous `bag_of_words` function. 
(*for extra challenge, try to code the function in one-line*)

Here, I've included a positive and negative wordlist that I constructed by hand. Due to copyright issues, we are not able to provide other commonly used wordlists. I encourage you to try out different wordlists on your own.

<a href="#table_of_content">back to top</a>

In [6]:
# load wordlist first
import pickle

with open('positive_words.pickle', 'rb') as f:
    positive_words = pickle.load(f)
    # also need to stem and lemmatize the text
    positive_words = set(clean_text(" ".join(positive_words)))
    
with open('negative_words.pickle', 'rb') as f:
    negative_words = pickle.load(f)
    negative_words = set(clean_text(" ".join(negative_words)))
    
# check out the list
# print("positive words: ", positive_words)
print(positive_words)
# print("negative words: ", negative_words)
print(negative_words)

{'motiv', 'dazzl', 'award', 'meritori', 'brilliant', 'abund', 'prodigi', 'applaus', 'attract', 'improv', 'strength', 'gift', 'delight', 'astonish', 'exhilar', 'restor', 'optimist', 'cheer', 'accomplish', 'superb', 'upbeat', 'boost', 'terrif', 'endors', 'fortun', 'happi', 'groundbreak', 'heal', 'transform', 'enhanc', 'honor', 'stabl', 'strong', 'perfect', 'prestigi', 'insight', 'aptitud', 'exuber', 'opportun', 'trendi', 'fantast', 'actual', 'celebr', 'complet', 'invent', 'fabul', 'love', 'reliev', 'clear', 'except', 'recoveri', 'lucrat', 'nobl', 'forefront', 'harmoni', 'succeed', 'enthusiasm', 'growth', 'profici', 'approv', 'pleasant', 'loyal', 'reinforc', 'benefici', 'ador', 'legendari', 'distinct', 'master', 'recov', 'better', 'booster', 'compliment', 'exemplifi', 'impress', 'relief', 'favor', 'fresh', 'earnest', 'promin', 'tremend', 'product', 'acclaim', 'famous', 'boon', 'achiev', 'prais', 'nobli', 'beauti', 'happili', 'buoy', 'popular', 'jubil', 'bless', 'lead', 'safe', 'magic', 's

In [7]:
def get_sentiment(txt, wordlist):
    matching_words = [ w for w in txt if w in wordlist ]
    return len(matching_words)/len(txt)

In [8]:
# test your function
positive_sentiments = np.array([ get_sentiment(c, positive_words) for c in corpus ])
print(positive_sentiments)

negative_sentiments = np.array([ get_sentiment(c, negative_words) for c in corpus ])
print(negative_sentiments)

[ 0.034  0.033  0.034  0.031  0.032  0.039  0.039  0.037  0.033  0.04 ]
[ 0.051  0.05   0.054  0.061  0.061  0.062  0.061  0.06   0.059  0.059]


**before continuing part 2, go through the lesson material first!**

<a id="compute_idf"></a>

# Part 2 Document Vector Exercises

## 3. Computer idf
Given a corpus, or a list of bag-of-words, we want to compute for each word $w$, the inverse-document-frequency, or ${\rm idf}(w)$. This can be done in a few steps:

1. Gather a set of all the words in all the bag-of-words (python set comes in handy, and the union operator `|` is useful here)


2. Loop over each word $w$, and compute ${\rm df}_w$, the number of documents where this word appears at least once. A dictionary is useful for keeping track of ${\rm df}_w$


3. After computing ${\rm df}_w$, we can compute ${\rm idf}(w)$. There are usually two possibilities, the simplest one is 
$${\rm idf}(w)=\frac{N}{{\rm df}_w}$$
Where $N$ is the total number of documents in the corpus and $df_w$ the number of documents that contain the word $w$. Frequently, a logarithm term is added as well
$${\rm idf}(w)=\log\frac{N}{{\rm df}_w}$$
One issue with using the logarithm is that when ${\rm df}_w = N$, ${\rm idf}(w)=0$, indicating that words common to all documents would be ignored. If we don't want this behavior, we can define ${\rm idf}(w)=\log\left(1+N/{\rm df}_w\right)$ or ${\rm idf}(w)=1+\log\left(N/{\rm df}_w\right)$ instead. For us, we'll not use the extra +1 for ${\rm idf}$.

In the following, define a function called `get_idf(corpus, include_log=True)` that computes ${\rm idf}(w)$ for all the words in a corpus, where `corpus` for us is a processed list of bag-of-words (stemmed and lemmatized). The optional parameter `include_log` includes the logarithm in the computation.

<a href="#table_of_content">back to top</a>

In [11]:
# compute idf
import numpy as np
def get_idf(corpus, include_log=True):
    N = len(corpus)
    freq = defaultdict(int)
    words = set()
    for c in corpus:
        words |= set(c)        
    for w in words:
        freq[w] = sum([ w in c for c in corpus])

    if include_log:
        return { w: np.log(N/freq[w]) for w in freq }
    else:
        return { w: N/freq[w] for w in freq }

You should expect to see many idf values = 0! This is by design, because we have ${\rm idf}(w)=\log N_d/{\rm df}_w$ and $N_d/{\rm df}_w=1$ for the most common words!

In [12]:
# test your code
idf=get_idf(corpus)
print_sorted(idf, ascending=True)

deliveri: 0.000
lengthi: 0.000
declin: 0.000
januari: 0.000
indirect: 0.000
indic: 0.000
rat: 0.000
good: 0.000
secur: 0.000
choos: 0.000
ultim: 0.000
consum: 0.000
asset: 0.000
valu: 0.000
perform: 0.000
incom: 0.000
state: 0.000
whether: 0.000
share: 0.000
damag: 0.000
parti: 0.000
shop: 0.000
aggress: 0.000
rise: 0.000
control: 0.000
opportun: 0.000
regul: 0.000
satisfi: 0.000
deliv: 0.000
depend: 0.000
time: 0.000
agreement: 0.000
sourc: 0.000
discourag: 0.000
liquid: 0.000
involv: 0.000
high: 0.000
relat: 0.000
current: 0.000
affect: 0.000
common: 0.000
custom: 0.000
appropri: 0.000
properti: 0.000
industri: 0.000
suffici: 0.000
make: 0.000
econom: 0.000
whose: 0.000
credit: 0.000
locat: 0.000
key: 0.000
fluctuat: 0.000
natur: 0.000
statement: 0.000
annual: 0.000
procedur: 0.000
confid: 0.000
expans: 0.000
continu: 0.000
general: 0.000
accord: 0.000
experi: 0.000
oper: 0.000
barrier: 0.000
amount: 0.000
avail: 0.000
financ: 0.000
disput: 0.000
disrupt: 0.000
materi: 0.000
threat: 

<a id="compute_tf"></a>

## 4. Compute tf

Below we will compute ${\rm tf}(w,d)$, or the term frequency for a given word $w$, in a given document $d$. Since our ultimate goal is to compute a document vector, we'd like to keep a few things in mind

1. Store the ${\rm tf}(w, d)$ for each word in a document as a dictionary
2. Even when a word doesn't appear in the document $d$, we still want to keep a $0$ entry in the dictionary. This is important when we convert the dictionary to a vector, where zero entries are important


There are multiple definitions for ${\rm tf}(w,d)$, the simplest one is

$$
{\rm tf}(w,d)=\frac{f_{w,d}}{a_d}
$$

where $f_{w,d}$ is the number of occurence of the word $w$ in the document $d$, and $a$ the average occurence of all the words in that document for normalization. Just like ${\rm idf}(w)$, a logarithm can be added

$$
{\rm tf}(w,d)=\begin{cases}
\frac{1+\log f_{w,d}}{1+\log a_d} & f_{w,d} > 0 \\
0 & f_{w,d} = 0 \\
\end{cases}
$$

Implement the function `get_df(txt, include_log=True)` that computes ${\rm tf}(w,d)$ for each word in the document (returns a defaultdict(int), so that when supplying words not in the document the dictionary will yield zero instead of an error). Also include the optional parameter `include_log` that enables the additional logarithm term in the computation. I suggest also adding a function called `_tf` that computes the function above. 

<a href="#table_of_content">back to top</a>

In [13]:
import numpy as np
from math import *

def _tf(freq, avg, include_log=True):
    # TO DO
    if include_log:
        return 0 if freq == 0 else (1+ np.log(freq)) / (1 + np.log(avg))
    else:
        return freq/avg

def get_tf(txt, include_log=True):
    # TO DO
    freq = bag_of_words(txt)
    avg = np.mean(list(freq.values()))
    tf = {w:_tf(f,avg, include_log) for w,f in freq.items()}
    return defaultdict(int, tf)

In [14]:
tfs = [ get_tf(c) for c in corpus ]
print_sorted(tfs[0])

paypal: 2.090
payment: 1.989
increas: 1.902
custom: 1.900
regul: 1.837
provid: 1.824
addit: 1.815
transact: 1.803
new: 1.796
use: 1.791
seller: 1.778
websit: 1.770
gsi: 1.764
abil: 1.747
consum: 1.744
oper: 1.735
harm: 1.729
certain: 1.723
subject: 1.717
mobil: 1.707
internet: 1.704
time: 1.693
onlin: 1.690
ebay: 1.686
advers: 1.679
relat: 1.672
offer: 1.660
card: 1.660
sale: 1.657
site: 1.657
would: 1.653
risk: 1.649
bank: 1.649
affect: 1.645
client: 1.645
signific: 1.628
action: 1.628
buyer: 1.628
platform: 1.619
fund: 1.619
bill: 1.619
continu: 1.615
revenu: 1.615
state: 1.615
effect: 1.610
make: 1.610
local: 1.601
activ: 1.596
applic: 1.596
protect: 1.587
regulatori: 1.587
number: 1.587
credit: 1.582
countri: 1.577
ecommerc: 1.577
later: 1.577
right: 1.572
account: 1.561
merchant: 1.556
process: 1.556
good: 1.556
inform: 1.550
receiv: 1.550
practic: 1.545
parti: 1.545
intern: 1.545
manag: 1.539
loss: 1.533
rate: 1.522
develop: 1.522
system: 1.522
liabil: 1.522
reduc: 1.522
network:

<a id="doc_vector"></a>

## 5. Document Vector
Combine the implementation for ${\rm tf}(w,d)$ and ${\rm idf}(w)$ to compute a word-vector for each document in a corpus. Don't forget the zero-padding that is needed when a word appears in some document but not others. 

Implmenet the function `get_vectors(tf,idf)`, the input is the output computed by `get_tf` and `get_idf`

(*optional challenge: implement in one line!*)

<a href="#table_of_content">back to top</a>

In [15]:
def get_vector(tf, idf):
    return np.array([ tf[w]*idf[w] for w in idf ])

In [16]:
# test your code
doc_vectors = [ get_vector(tf, idf) for tf in tfs ]

for v in doc_vectors:
    print(v)

[ 0.497  0.449  0.214 ...,  0.841  0.51   0.658]
[ 0.484  1.182  0.208 ...,  0.819  0.497  0.665]
[ 0.     1.166  0.225 ...,  0.     0.225  0.614]
[ 0.     0.251  0.251 ...,  0.     0.251  0.545]
[ 0.     0.248  0.248 ...,  0.     0.248  0.539]
[ 0.  0.  0. ...,  0.  0.  0.]
[ 0.  0.  0. ...,  0.  0.  0.]
[ 0.  0.  0. ...,  0.  0.  0.]
[ 0.  0.  0. ...,  0.  0.  0.]
[ 0.     0.     0.    ...,  0.     0.     0.359]


<a id ="similarity"></a>

## 6. Similarity

Given two word-vectors $\vec u$ (or $u_i$) and $\vec v$ (or $v_i$), corresponding to two documents, we want to compute different similarity metrics. 

1. Cosine similarity, defined by 
$$
{\rm Sim}_{\cos} = \frac{\vec u \cdot \vec v}{|\vec u| |\vec v|}
$$

2. Jaccard similarity, defined by
$$
{\rm Sim}_{\rm Jaccard} = \frac{\sum_i \min\{u_i, v_i\}}{\sum_i \max\{u_i, v_i\}}
$$

Implement the function similarity as `sim_cis(u,v)` and `sim_jac(u,v)`. Utilize the numpy functions `numpy.linalg.norm` to compute norm of a vector and `np.dot` for computing dot-products. `np.minimum` and `np.maximum` are also useful vectorized pair-wise minimum and maximum functions.

(*optional challenge: implement both functions in one line!*)

<a href="#table_of_content">back to top</a>

In [19]:
from numpy.linalg import norm

def sim_cos(u,v):
    # TO DO
    return (u @ v) / (norm(u) * norm(v))

def sim_jac(u,v):
    # TO DO
    return np.sum(np.minimum(u,v))/np.sum(np.maximum(u,v))

In [20]:
# test your co
# compute all the pairwise similarity metrics
size = len(doc_vectors)
matrix_cos = np.zeros((size,size))
matrix_jac = np.zeros((size,size))

for i in range(size):
    for j in range(size):
        u = doc_vectors[i]
        v = doc_vectors[j]
        matrix_cos[i][j] = sim_cos(u,v)
        matrix_jac[i][j] = sim_jac(u,v)
        
print("Cosine Similarity:")
print(matrix_cos)

print()
print("Jaccard Similarity:")
print(matrix_jac)

Cosine Similarity:
[[ 1.     0.884  0.585  0.475  0.479  0.02   0.019  0.015  0.057  0.164]
 [ 0.884  1.     0.594  0.454  0.455  0.018  0.017  0.014  0.05   0.158]
 [ 0.585  0.594  1.     0.65   0.653  0.015  0.015  0.011  0.056  0.162]
 [ 0.475  0.454  0.65   1.     0.949  0.012  0.012  0.007  0.053  0.149]
 [ 0.479  0.455  0.653  0.949  1.     0.014  0.013  0.008  0.054  0.149]
 [ 0.02   0.018  0.015  0.012  0.014  1.     0.878  0.758  0.508  0.187]
 [ 0.019  0.017  0.015  0.012  0.013  0.878  1.     0.873  0.582  0.209]
 [ 0.015  0.014  0.011  0.007  0.008  0.758  0.873  1.     0.666  0.228]
 [ 0.057  0.05   0.056  0.053  0.054  0.508  0.582  0.666  1.     0.325]
 [ 0.164  0.158  0.162  0.149  0.149  0.187  0.209  0.228  0.325  1.   ]]

Jaccard Similarity:
[[ 1.     0.793  0.425  0.296  0.297  0.007  0.008  0.008  0.024  0.114]
 [ 0.793  1.     0.424  0.279  0.28   0.007  0.008  0.007  0.022  0.107]
 [ 0.425  0.424  1.     0.505  0.506  0.007  0.009  0.008  0.029  0.128]
 [ 0.296  

### Good Job! You've finished all the exercises!

Here is an optional bonus challenge. We often need to debug other people's code to figure out what's wrong. It's particularly difficult when the code doesn't give errors but computes the wrong quantity. Can you describe why the following implementations for some of the exercises above may be wrong? Highlight the words at the bottom to reveal the solutions!

In [ ]:
def get_idf_wrong(corpus, include_log=True):
    freq = defaultdict(int)
    for c in corpus:
        for w in c:
            freq[w] += 1
        
    N = len(corpus)
    if include_log:
        return { w:log(N/freq[w]) for w in freq }
    else:
        return { w:N/freq[w] for w in freq }


def get_sentiment_wrong(txt, wordlist):
    matching_words = [ w for w in wordlist if w in txt ]
    return len(matching_words)/len(txt)

def get_vectors_wrong(tf, idf):
    return np.array([ tf[w]*idf[w] for w in tf ])

# Solutions

Drag your mouse over the white space below this cell, and you'll see details about the solutions.  Or, if it's easier, just double-click on the white space below this cell, which will reveal the cell with hidden text.  Also, please check out the file [bagofwords_solutions.py](bagofwords_solutions.py).

<font color="white">
Solution

get_idf: the defaultdict freq here computes the total number of occurences in all the document. We only want to count it once when a word appears in a document. This may lead to a document frequency larger than N, leading to a negative idf! 

get_sentiment_wrong: if a word w appears twice in the document, it won't be counted properly!

get_vectors_wrong: tf may not contain all the words in idf. We need zero padding for words that appear in idf but not in tf! 
</font> 